baseURL = "https://nautilusinfo.com/"
languageCode = "pt-br"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Sobre"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Contato"
  URL = "#contact"
  weight = 3


  [[menu.footer]]
  name = "Política de Privacidade"
  URL = "#privacy"
  weight = 1


[params]

  sections = ["showcase", "about", "privacy", "contact"]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Nautilus"
    text2 = "Sistemas"

  [params.footer]
      copyright = "© Raditian. All rights reserved."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"